kafka.bootstrap.servers=localhost:9092
schema.registry.url=http://localhost:8081
schema.subject=dobby-events-value
kafka.topic=dobby-events

# Consumer Group
kafka.consumer.group-id=dobby-consumer-group
kafka.consumer.group-id.backward.v1=dobby-backward-v1-group
kafka.consumer.group-id.backward.v2=dobby-backward-v2-group
kafka.consumer.group-id.forward.v1=dobby-forward-v1-group
kafka.consumer.group-id.forward.v2=dobby-forward-v2-group
