kafka.bootstrap.servers=localhost:9092
schema.registry.url=http://localhost:8081
schema.subject=dobby-events-value
kafka.topic=dobby-events

# Consumer Group
kafka.consumer.group-id=dobby-consumer-group
kafka.consumer.group-id.backward=dobby-backward-group
kafka.consumer.group-id.forward=dobby-forward-group
